Update the GitHub Actions
The change to the required Qt version is due to errors such as
“qvarlengtharray.h(683): error C3861: ‘stdext’: identifier not found”,
 which unexpectedly occurred when running GitHub Actions.